### PR TITLE
BUG: fix parsing upload time

### LINKED ISSUE #8: Wheel upload failed with time format error
Example log:

```
  File "python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-02-16 04:19:43+00:00' does not match format '%Y-%m-%d %H:%M:%S.%f%z'
Error: Process completed with exit code 1.
```

https://github.com/astropy/astropy/actions/runs/7954387476/job/21712087501

### PR DESCRIPTION
**Pull request by neutrinoceros**
This adresses an issue noticed downstream at https://github.com/astropy/astropy/issues/16076, where a crash would occur when cleaning old wheels as the upload time stamp wouldn't match the expected format.
I have limited understanding of everything that's going on here so this might not be the correct approach, but it seemed simple enough. I've assumed that both the old and new timestamp format could still be in use so I wouldn't break backward compatibility, but maybe that's not important ?

### CODE REVIEW

**Comment by Cadair** [comment]
Thanks @neutrinoceros I will let @astrofrog or @ConorMacBride look over this as they understand it unlike me!

**Comment by pllim** [comment]
I don't understand the failure but doesn't seem related?

```
Error:  ('Authorization header was not given', 401)
Error: Process completed with exit code 1.
```

Thanks for the quick fix! Hopefully it can be merged soon. If I have to wait a while to be able to upload a nightly wheel again, I might take Brigitta's suggestion to try out the Scientific Python workflow (xref https://github.com/OpenAstronomy/publish-wheels-anaconda/issues/7). So please let me know if you are unable to get to this by the end of the week. Thanks!

**Comment by pllim** [comment]
p.s. I wonder if there is a better way to future-proof in case the server changes the time formatting again.

**Comment by ConorMacBride** [comment]
Thanks @neutrinoceros! As @pllim suggests it would be good to future-proof the parsing, but we can decide that in a different PR so we get the fix out now.

One option would be to use the dateutil package to parse without specifying a format. Another would be to use regex to extract just a date (`[0-9]{4}-[0-9]{2}-[0-9]{2}`) as the time is unlikely to be necessary in most cases.

**Comment by ConorMacBride** [comment]
It is only one specific wheel build that has the different time format (`astropy-6.1.dev455+gaeeed0886e-cp39-cp39-musllinux_1_1_x86_64.whl` from `2024-02-16 04:19:43+00:00`). Everything else is still using the existing format including the latest uploads.

The test failures in this PR are due to PRs not having access to secrets.

**Comment by neutrinoceros** [comment]
I tend to prefer solutions that don't require new dependencies so if a regexp suffices, I can craft a more general solution tomorrow !

**Review by ConorMacBride — APPROVED** [review]

**Comment by pllim** [comment]
Moment of truth is approaching... https://github.com/astropy/astropy/actions/runs/7979290389

**Comment by pllim** [comment]
dev483 uploaded successfully. Thanks, all!

**Pull request merged**
